### ISSUE TITLE
Concatenating circuits that share input

### ISSUE THREAD

**Issue by thesamet** [osimon8/CombinatorC#2]
Thanks for putting together this project!

I would like to be able to re-use some expression (`myexpr` below) in multiple circuits. I think the only way it's currently possible with `CombinatorC` is to assign that expression as a signal.

So I go like this:

```
circuit myexpr: R = X < 20000 && Y < 20000;

circuit cl: L = X < Y && R;

output myexpr @ cl;
```

The problem is that `cl` also depends on `X` and `Y`. The constant combinator generated for input would have entries for `X` and `Y` twice (looks like a bug?), and would not pass through the `X` and `Y` from that constant combinator to the expression computed by `L`.

Is this way of combining circuits supported?

**Comment by osimon8** [comment]
Latest release added an "expression" variable type that should do exactly what you want - you would write your code like this:

```
expression myexpr = X < 20000 && Y < 20000;

circuit cl: L = X < Y && myexpr;

output cl;
```
